name: package
default-extensions:
  - OverloadedStrings
  - ExtendedDefaultRules
  - ApplicativeDo
  - BlockArguments
  - LambdaCase
dependencies:
  - base >= 4.19 && < 5
  - array
  - containers
  - text
  - optparse-applicative
  - shelly
  - yaml
description: package for building helper programs
executables: 
  start-advent:
    main: StartAdvent.Main
    source-dirs:
      - ./app/Advent/
  run-advent:
    main: RunAdvent.Main
    source-dirs:
      - ./app/Advent/
