name:                 Day21
version:              0.1.0.0
visibility:           public
id:                   Day21-0.1.0.0-inplace
key:                  Day21-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2021 Mitch Stevens
maintainer:           mitchstevens95@gmail.com
author:               Mitch Stevens
homepage:             https://github.com/MitchStevens/Day21#readme
description:
    Please see the README on GitHub at <https://github.com/MitchStevens/Day21#readme>

abi:                  inplace
exposed:              True
exposed-modules:      Lib
hidden-modules:       Paths_Day21
import-dirs:
    /home/mitch/Repos/AoC/2020/Day21/dist-newstyle/build/x86_64-linux/ghc-8.10.4/Day21-0.1.0.0/build

library-dirs:
    /home/mitch/Repos/AoC/2020/Day21/dist-newstyle/build/x86_64-linux/ghc-8.10.4/Day21-0.1.0.0/build

dynamic-library-dirs:
    /home/mitch/Repos/AoC/2020/Day21/dist-newstyle/build/x86_64-linux/ghc-8.10.4/Day21-0.1.0.0/build

data-dir:             /home/mitch/Repos/AoC/2020/Day21/.
hs-libraries:         HSDay21-0.1.0.0-inplace
depends:              base-4.14.1.0
haddock-interfaces:
    /home/mitch/Repos/AoC/2020/Day21/dist-newstyle/build/x86_64-linux/ghc-8.10.4/Day21-0.1.0.0/doc/html/Day21/Day21.haddock

haddock-html:
    /home/mitch/Repos/AoC/2020/Day21/dist-newstyle/build/x86_64-linux/ghc-8.10.4/Day21-0.1.0.0/doc/html/Day21
